#! /bin/sh
### BEGIN INIT INFO
# Provides:          Start VOIP-Software for rotary-dial phone 
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start VOIP-Software for rotary-dial phone
# Description:       Start VOIP-Software for rotary-dial phone
### END INIT INFO
# Author: Name <andreas.gschossmann@hs-regensburg.de>

# Aktionen
case "$1" in
    start)
        python /opt/voip-software.py
        ;;
    stop)
	linphonecsh exit
        ;;
    restart)
	linphonecsh exit
        ;;
esac

exit 0
